import AppKit
import RotoCore

extension NSPasteboard.PasteboardType {
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let jpeg = NSPasteboard.PasteboardType("public.jpeg")
    static let heic = NSPasteboard.PasteboardType("public.heic")
}

@MainActor
final class ClipboardMonitor {
    private var timer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount
    let history: ClipboardHistory
    let images: ClipboardImageStore
    var includeImages = true
    var ignoreApps: Set<String> = []
    var persist = false
    var onChange: (() -> Void)?
    private var didLoadPersist = false
    /// Image capture, loading, saving and cleanup all run here. Being serial keeps
    /// captures in copy order and never lets cleanup delete an image mid-capture.
    private let workQueue = DispatchQueue(label: "roto.clipboard.work", qos: .userInitiated)
    private var syncScheduled = false
    private var lastExpiryCheck = Date()

    private static let textTypes: [NSPasteboard.PasteboardType] = [.string, .rtf, .rtfd, .html]
    private static let imageTypes: [NSPasteboard.PasteboardType] = [.png, .tiff, .jpeg, .heic]

    init(history: ClipboardHistory, images: ClipboardImageStore) {
        self.history = history
        self.images = images
    }

    func start() {
        lastChangeCount = NSPasteboard.general.changeCount
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.poll()
            }
        }
        timer?.tolerance = 0.1
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func apply(config: Config.Clipboard) {
        includeImages = config.includeImages
        ignoreApps = Set(config.ignoreApps)
        persist = config.persist
        history.setCapacity(config.historySize)
        history.setMaxAge(config.maxAgeDays > 0 ? TimeInterval(config.maxAgeDays) * 86_400 : nil)
        onChange?()
        let directory = persist ? Paths.clipboardImagesDirectory : nil
        workQueue.async { [images, history] in
            images.relocate(to: directory, keeping: history.imageDigests)
            if directory == nil {
                // Saving is off: images left by an earlier run go too.
                try? FileManager.default.removeItem(at: Paths.clipboardImagesDirectory)
            }
        }
        if persist, !didLoadPersist {
            loadPersisted()
            didLoadPersist = true
        }
        scheduleSync()
    }

    /// Puts an entry back on the clipboard and moves it to the top of history.
    func write(_ item: ClipboardItem) {
        let board = NSPasteboard.general
        board.clearContents()
        if let urls = item.fileURLs, !urls.isEmpty {
            let entries = urls.map { url -> NSPasteboardItem in
                let entry = NSPasteboardItem()
                entry.setString(url.absoluteString, forType: .fileURL)
                return entry
            }
            if let text = item.text {
                entries[0].setString(text, forType: .string)
            }
            board.writeObjects(entries)
        } else {
            let entry = NSPasteboardItem()
            if let text = item.text {
                entry.setString(text, forType: .string)
            }
            if let image = item.image, let png = images.data(for: image) {
                entry.setData(png, forType: .png)
            }
            board.writeObjects([entry])
        }
        // Our own write is not a new copy: keep the original source app and date order.
        lastChangeCount = board.changeCount
        history.promote(item.id)
        didChange()
    }

    func remove(_ item: ClipboardItem) {
        history.remove(item.id)
        didChange()
    }

    private func poll() {
        let board = NSPasteboard.general
        // Age out old entries even when nothing new is copied for days.
        if Date().timeIntervalSince(lastExpiryCheck) > 3_600 {
            lastExpiryCheck = Date()
            if history.removeExpired() {
                didChange()
            }
        }
        let count = board.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        capture(board)
    }

    private func capture(_ board: NSPasteboard) {
        let types = board.types ?? []
        if types.contains(.concealed) || types.contains(.transient) || types.contains(.autoGenerated) {
            return
        }
        let front = NSWorkspace.shared.frontmostApplication
        if let bid = front?.bundleIdentifier, ignoreApps.contains(bid) {
            return
        }

        var text = board.string(forType: .string)
        if text?.isEmpty == true { text = nil }

        let fileURLs = board.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL]
        if let fileURLs, !fileURLs.isEmpty {
            add(ClipboardItem(text: text, fileURLs: fileURLs, appName: front?.localizedName, bundleID: front?.bundleIdentifier))
            return
        }

        // Spreadsheets and office apps put a picture of the text next to the text.
        // Keep the image only when it is the primary thing that was copied.
        let firstImage = types.firstIndex { Self.imageTypes.contains($0) }
        let firstText = types.firstIndex { Self.textTypes.contains($0) }
        let imageIsPrimary = firstImage != nil && (firstText == nil || firstImage! < firstText!)
        guard includeImages, imageIsPrimary else {
            add(ClipboardItem(text: text, appName: front?.localizedName, bundleID: front?.bundleIdentifier))
            return
        }

        let png = board.data(forType: .png)
        let raw = png == nil ? Self.imageTypes.lazy.compactMap { board.data(forType: $0) }.first : nil
        let appName = front?.localizedName
        let bundleID = front?.bundleIdentifier
        workQueue.async { [weak self, history, images, text] in
            // The history only keeps a digest; the bytes go to the store and leave memory here.
            let image = autoreleasepool {
                (png ?? raw.flatMap(Self.pngData)).flatMap(images.put)
            }
            let item = ClipboardItem(text: text, image: image, appName: appName, bundleID: bundleID)
            guard !item.isEmpty else { return }
            history.add(item)
            DispatchQueue.main.async {
                self?.didChange()
            }
        }
    }

    private func add(_ item: ClipboardItem) {
        guard !item.isEmpty else { return }
        history.add(item)
        didChange()
    }

    private func didChange() {
        onChange?()
        scheduleSync()
    }

    /// Coalesces bursts of copies into one save and one image cleanup, off the main thread.
    private func scheduleSync() {
        guard !syncScheduled else { return }
        syncScheduled = true
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) { [weak self] in
            guard let self else { return }
            self.syncScheduled = false
            let persist = self.persist
            self.workQueue.async { [history, images] in
                images.prune(keeping: history.imageDigests)
                if persist {
                    Self.persist(history)
                }
            }
        }
    }

    nonisolated private static func persist(_ history: ClipboardHistory) {
        do {
            try FileManager.default.createDirectory(at: Paths.supportDirectory, withIntermediateDirectories: true)
            let data = try history.encode()
            let url = Paths.clipboardFile
            try data.write(to: url, options: .atomic)
            try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
        } catch {
            // Keep going; persistence is best-effort.
        }
    }

    private func loadPersisted() {
        let capacity = history.capacity
        workQueue.async { [weak self, history, images] in
            let url = Paths.clipboardFile
            guard FileManager.default.fileExists(atPath: url.path),
                  let data = try? Data(contentsOf: url),
                  let loaded = try? ClipboardHistory.decode(from: data, capacity: capacity, store: images)
            else { return }
            // Anything copied since launch is newer than what was on disk.
            history.appendOlder(loaded.all)
            DispatchQueue.main.async {
                // Saving again also rewrites files from older versions without inline images.
                self?.didChange()
            }
        }
    }

    nonisolated private static func pngData(_ data: Data) -> Data? {
        autoreleasepool {
            NSBitmapImageRep(data: data)?.representation(using: .png, properties: [:])
        }
    }
}
